version: '3.7'

services:
  database:
    image: postgres:latest
    container_name: ip_retrieval_process_database
    volumes:
      - ".postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE_NAME}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  rabbitmq:
    image: rabbitmq:3-management
    container_name: ip_retrieval_process_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "8082:15672"

networks:
  default:
    driver: bridge
    name: "ip-retrieval-process"
